### ISSUE TITLE
How to set batch size?

### ISSUE THREAD

**Issue by Luoyadan** [simonguist/testing-fcn-for-cityscapes#1]
I tried this code to train a fcn on cityscapes, yet I found the batch size might not be changed in solve_start.py. could you please explain a little bit about this? Thanks

**Comment by simonguist** [comment]
Sorry for the late reply.
Training is done on whole images, as suggested by Shelhamer et al. So you don't have to set a batch size.
If training is to heavy on your GPU you might want to downscale the images before doing training (downscale_images.py)
