### ISSUE TITLE
only get mIOU 56% on cityscape dataset

### ISSUE THREAD

**Issue by xhnie** [simonguist/testing-fcn-for-cityscapes#2]
Hi Simon,

I downloaded your weight file "cityscapes-fcn8s-2x.caffemodel" and used the "deploy_8s.prototxt" for evaluation on the 500 validation images of cityscape, however, I only got 56% mean class IOU. I followed the evaluation code on your github. Do you think it is a reasonable result on this model file? Do you have another model file which can achieve 60.8% mentioned in your report? Thanks so much!

Best,

**Comment by simonguist** [comment]
Hi,
this is the final model, so it should be expected to perform better than your result.
Did you downscale the images before the evaluation?

**Comment by xhnie** [comment]
I figured it out. I used the wrong mean value. Now I can get the same result as in your report. Thanks so much for sharing the code. btw, have you trained any other models for segmentation on cityscapes? such as PSPnet or ICnet?

**Comment by simonguist** [comment]
Happy to hear that you figured it out. This is the only model I trained for cityscapes
